# Generated by Django 3.2.8 on 2021-10-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImportExport', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
